
set -Ux SDL_VIDEODRIVER wayland
set -Ux _JAVA_AWT_WM_NONREPARENTING 1
set -Ux QT_QPA_PLATFORM wayland
set -Ux XDG_CURRENT_DESKTOP sway
set -Ux XDG_SESSION_DESKTOP "sway"

set -Ux WLR_NO_HARDWARE_CURSORS 1
set -Ux GDK_BACKEND wayland
set -Ux CLUTTER_BACKEND wayland
set -Ux SDL_VIDEODRIVER wayland
set -Ux XDG_SESSION_TYPE wayland
