# Autogenerated by matugen – DO NOT EDIT MANUALLY

def apply(c):
    # Backgrounds / Foregrounds
    c.colors.background = "{{colors.background.default.hex}}"
    c.colors.foreground = "{{colors.on_background.default.hex}}"

    # Statusbar
    c.colors.statusbar.normal.bg = "{{colors.surface.default.hex}}"
    c.colors.statusbar.normal.fg = "{{colors.on_surface.default.hex}}"

    c.colors.statusbar.insert.bg = "{{colors.primary.default.hex}}"
    c.colors.statusbar.insert.fg = "{{colors.on_primary.default.hex}}"

    c.colors.statusbar.command.bg = "{{colors.surface_variant.default.hex}}"
    c.colors.statusbar.command.fg = "{{colors.on_surface_variant.default.hex}}"

    c.colors.statusbar.url.fg = "{{colors.primary.default.hex}}"
    c.colors.statusbar.url.success.http.fg = "{{colors.tertiary.default.hex}}"
    c.colors.statusbar.url.success.https.fg = "{{colors.tertiary.default.hex}}"
    c.colors.statusbar.url.error.fg = "{{colors.error.default.hex}}"
    c.colors.statusbar.url.warn.fg = "{{colors.secondary.default.hex}}"

    # Tabs
    c.colors.tabs.bar.bg = "{{colors.background.default.hex}}"

    c.colors.tabs.even.bg = "{{colors.surface.default.hex}}"
    c.colors.tabs.even.fg = "{{colors.on_surface.default.hex}}"

    c.colors.tabs.odd.bg = "{{colors.surface.default.hex}}"
    c.colors.tabs.odd.fg = "{{colors.on_surface.default.hex}}"

    c.colors.tabs.selected.even.bg = "{{colors.primary.default.hex}}"
    c.colors.tabs.selected.even.fg = "{{colors.on_primary.default.hex}}"

    c.colors.tabs.selected.odd.bg = "{{colors.primary.default.hex}}"
    c.colors.tabs.selected.odd.fg = "{{colors.on_primary.default.hex}}"

    # Hints
    c.colors.hints.bg = "{{colors.secondary.default.hex}}"
    c.colors.hints.fg = "{{colors.on_secondary.default.hex}}"
    c.colors.hints.match.fg = "{{colors.primary.default.hex}}"

    # Downloads
    c.colors.downloads.bar.bg = "{{colors.surface.default.hex}}"
    c.colors.downloads.start.bg = "{{colors.primary.default.hex}}"
    c.colors.downloads.start.fg = "{{colors.on_primary.default.hex}}"
    c.colors.downloads.stop.bg = "{{colors.tertiary.default.hex}}"
    c.colors.downloads.stop.fg = "{{colors.on_tertiary.default.hex}}"
    c.colors.downloads.error.bg = "{{colors.error.default.hex}}"
    c.colors.downloads.error.fg = "{{colors.on_error.default.hex}}"

    # Messages
    c.colors.messages.info.bg = "{{colors.surface.default.hex}}"
    c.colors.messages.info.fg = "{{colors.on_surface.default.hex}}"

    c.colors.messages.warning.bg = "{{colors.secondary.default.hex}}"
    c.colors.messages.warning.fg = "{{colors.on_secondary.default.hex}}"

    c.colors.messages.error.bg = "{{colors.error.default.hex}}"
    c.colors.messages.error.fg = "{{colors.on_error.default.hex}}"

